import json
from typing import Callable, Dict

from omni.domain.catalog import get_asset_source
from omni.domain.formatting import fmt_num, fmt_pct
from omni.domain.models import MarketSentiment, Quote
from omni.domain.ports import ReportExporterPort


def build_b2b_report(
    modulo: str,
    company_name: str,
    cnpi_code: str,
    now_str: str,
    lang_key: str,
    sentiment: MarketSentiment,
    categories: dict,
    quotes: Dict[str, Quote],
    is_category_enabled: Callable[[str], bool],
    is_asset_enabled: Callable[[str, str], bool],
) -> str:
    lines = [
        f"=== INSTITUTIONAL REPORT {modulo.upper()} (B2B) ===",
        f"Issuer: {company_name} | Analyst ID: {cnpi_code}",
        f"Timestamp: {now_str} | Language: {lang_key}",
        f"Market Sentiment: {sentiment.value} ({sentiment.classification})",
        "",
        "--- ASSETS & MONITORED CATEGORIES ---",
    ]
    for cat_name, cat_info in categories.items():
        if not is_category_enabled(cat_name):
            continue
        lines.append(f"\n[{cat_name.upper()}] (Tag: {cat_info['tag']})")
        for disp_name, ticker, currency in cat_info["assets"]:
            if not is_asset_enabled(cat_name, ticker):
                continue
            q = quotes.get(ticker) or Quote()
            src_name = get_asset_source(ticker)
            lines.append(f"  • {disp_name} ({ticker}) [{src_name}]: {currency} {fmt_num(q.price)} ({fmt_pct(q.change)})")
    return "\n".join(lines)


def build_youtube_script(now_str: str, modulo: str) -> str:
    return "\n".join([
        "=== YOUTUBE SCRIPT (AUTO-PILOT) ===",
        f"Timestamp: {now_str}",
        "",
        "[INTRODUCTION]",
        f"Market overview for {modulo} generated by OMNI Auto-Pilot.",
    ])


def build_whatsapp_message(now_str: str) -> str:
    return "\n".join(["=== WHATSAPP MESSAGE ===", f"OMNI Alert - {now_str}"])


def build_telegram_message(now_str: str) -> str:
    return "\n".join(["=== TELEGRAM MESSAGE ===", f"OMNI Official Channel | {now_str}"])


def export_to_json(modulo: str, lang_key: str, now_str: str, content: str) -> str:
    return json.dumps(
        {"module": modulo, "language": lang_key, "timestamp": now_str, "content": content},
        indent=4,
        ensure_ascii=False,
    )


def export_to_pdf(exporter: ReportExporterPort, content: str, company: str, now_str: str) -> bytes:
    return exporter.to_pdf(content, company, now_str)
